//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat_Fb_Message
    {
        public int Id { get; set; }
        public Nullable<int> FacebookIdReceived { get; set; }
        public string FacebookINameReceived { get; set; }
        public Nullable<int> Fb_TemplateMessageId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Chat_Fb_TemplateMessage Chat_Fb_TemplateMessage { get; set; }
        public virtual Chat_Fb_User Chat_Fb_User { get; set; }
    }
}
