//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrawlPostGroup_Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CrawlPostGroup_Post()
        {
            this.CrawlPostGroup_Action = new HashSet<CrawlPostGroup_Action>();
            this.CrawlPostGroup_Comment = new HashSet<CrawlPostGroup_Comment>();
            this.CrawlPostGroup_Privacy = new HashSet<CrawlPostGroup_Privacy>();
        }
    
        public int Id { get; set; }
        public string Fb_Id { get; set; }
        public string Message { get; set; }
        public string Picture { get; set; }
        public string Link { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public string Type { get; set; }
        public string StatusType { get; set; }
        public string ObjectId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<long> Shares { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public Nullable<bool> IsExpired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrawlPostGroup_Action> CrawlPostGroup_Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrawlPostGroup_Comment> CrawlPostGroup_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrawlPostGroup_Privacy> CrawlPostGroup_Privacy { get; set; }
    }
}
