//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrawlPostGroup_PostDetail
    {
        public int Id { get; set; }
        public Nullable<int> CrawlPostGroup_PostId { get; set; }
        public string Name { get; set; }
        public Nullable<long> UID { get; set; }
        public Nullable<long> ReactionTotalCount { get; set; }
        public Nullable<long> LikeCount { get; set; }
        public Nullable<long> LoveCount { get; set; }
        public Nullable<long> WowCount { get; set; }
        public Nullable<long> SupportCount { get; set; }
        public Nullable<long> HahaCount { get; set; }
        public Nullable<long> SadCount { get; set; }
        public Nullable<long> AngryCount { get; set; }
        public Nullable<long> ShareCount { get; set; }
        public Nullable<long> CommentCount { get; set; }
        public Nullable<System.DateTime> TimeCreatedInDb { get; set; }
        public Nullable<System.DateTime> TimeUpdatedInDb { get; set; }
    
        public virtual CrawlPostGroup_Post CrawlPostGroup_Post { get; set; }
    }
}
