//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrawlPostGroup_Comment
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string Message { get; set; }
        public Nullable<bool> CanRemove { get; set; }
        public Nullable<long> LikeCount { get; set; }
        public Nullable<bool> UserLike { get; set; }
        public string Fb_Id { get; set; }
        public Nullable<int> CrawlPostGroup_PostId { get; set; }
    
        public virtual CrawlPostGroup_Post CrawlPostGroup_Post { get; set; }
    }
}
