//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FbToolEntities : DbContext
    {
        public FbToolEntities()
            : base("name=FbToolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chat_Fb_BlockUser> Chat_Fb_BlockUser { get; set; }
        public virtual DbSet<Chat_Fb_Like_Post> Chat_Fb_Like_Post { get; set; }
        public virtual DbSet<Chat_Fb_Message> Chat_Fb_Message { get; set; }
        public virtual DbSet<Chat_Fb_Post> Chat_Fb_Post { get; set; }
        public virtual DbSet<Chat_Fb_TemplateMessage> Chat_Fb_TemplateMessage { get; set; }
        public virtual DbSet<Chat_Fb_Test> Chat_Fb_Test { get; set; }
        public virtual DbSet<Chat_Fb_User> Chat_Fb_User { get; set; }
        public virtual DbSet<Chat_Fb_User_Simsimi> Chat_Fb_User_Simsimi { get; set; }
        public virtual DbSet<Chat_NoiTuTiengAnhUser> Chat_NoiTuTiengAnhUser { get; set; }
        public virtual DbSet<Chat_NoiTuUser> Chat_NoiTuUser { get; set; }
        public virtual DbSet<CrawlPostGroup_Action> CrawlPostGroup_Action { get; set; }
        public virtual DbSet<CrawlPostGroup_Comment> CrawlPostGroup_Comment { get; set; }
        public virtual DbSet<CrawlPostGroup_Post> CrawlPostGroup_Post { get; set; }
        public virtual DbSet<CrawlPostGroup_PostDetail> CrawlPostGroup_PostDetail { get; set; }
        public virtual DbSet<CrawlPostGroup_Privacy> CrawlPostGroup_Privacy { get; set; }
        public virtual DbSet<Chat_Fb_FunnyStory> Chat_Fb_FunnyStory { get; set; }
    }
}
