//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FbToolEntities : DbContext
    {
        public FbToolEntities()
            : base("name=FbToolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fb_BlockUser> Fb_BlockUser { get; set; }
        public virtual DbSet<Fb_Like_Post> Fb_Like_Post { get; set; }
        public virtual DbSet<Fb_Message> Fb_Message { get; set; }
        public virtual DbSet<Fb_Post> Fb_Post { get; set; }
        public virtual DbSet<Fb_TemplateMessage> Fb_TemplateMessage { get; set; }
        public virtual DbSet<Fb_Test> Fb_Test { get; set; }
        public virtual DbSet<Fb_User> Fb_User { get; set; }
        public virtual DbSet<Fb_User_Simsimi> Fb_User_Simsimi { get; set; }
        public virtual DbSet<NoiTuUser> NoiTuUsers { get; set; }
        public virtual DbSet<Fb_FunnyStory> Fb_FunnyStory { get; set; }
        public virtual DbSet<NoiTuTiengAnhUser> NoiTuTiengAnhUsers { get; set; }
    }
}
