//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fb_User_Simsimi
    {
        public int Id { get; set; }
        public string FacebookId { get; set; }
        public string FacebookName { get; set; }
        public Nullable<bool> IsAgree { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
