using Google.Apis.Auth.OAuth2;
using Google.Apis.Download;
using Google.Apis.Drive.v3;
using Google.Apis.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;

namespace FacebookMessengerCsharp.Helper
{
    public class DownloadHelper
    {
        public static string DownloadImageFromUrl(string fileId)
        {
            string fileNameWithExtension = "girlxinh.jpg";
            // Thiết lập phạm vi truy xuất dữ liệu Scope = DriveReadonly để upload file
            string[] Scopes = { DriveService.Scope.DriveReadonly };
            string ApplicationName = "Download Image Tran Quang";
            UserCredential credential;
            credential = GoogleWebAuthorizationBroker.AuthorizeAsync(new ClientSecrets
            {
                ClientId = "621396650939-fm792s5cs3lhfs51nb77hclraledmjn7.apps.googleusercontent.com",
                ClientSecret = "JFoe_RqV-AM_Tb5NhLrf6yD8"
            },
                Scopes,
                "user", CancellationToken.None).Result;
            var driveService = new DriveService(new BaseClientService.Initializer()
            {
                HttpClientInitializer = credential,
                ApplicationName = ApplicationName,
            });
            // ID File lấy tài khoản Google Drive của bạn 
            var request = driveService.Files.Get(fileId);
            // Khai báo 1 MemoryStream để nhận kết quả tải về
            var streamDownload = new System.IO.MemoryStream();
            // Đăng ký phương thức thực hiện sự kiện ProgressChanged
            request.MediaDownloader.ProgressChanged +=
                    (IDownloadProgress progress) =>
                    {
                        switch (progress.Status)
                        {
                            case DownloadStatus.Downloading:
                                {
                                    Console.WriteLine(progress.BytesDownloaded);
                                    break;
                                }
                            case DownloadStatus.Completed:
                                {
                                    Console.WriteLine("Download complete.");
                                    // Hoàn thành việc tải file xuống MemoryStream thì thực hiện việc chuyển MemoryStream ra FileStream thực tế
                                    using (FileStream fs = new FileStream(fileNameWithExtension, FileMode.OpenOrCreate))
                                    {
                                        streamDownload.WriteTo(fs);
                                        fs.Flush();
                                    }
                                    break;
                                }
                            case DownloadStatus.Failed:
                                {
                                    Console.WriteLine("Download failed.");
                                    break;
                                }
                        }
                    };
            //https://drive.google.com/file/d/1RrjC8WAzqDKY0AClBiKCXQhmX7theAPC/view?usp=sharing
            // File được tải xuống dưới dạng MemoryStream lưu trong Ram
            request.Download(streamDownload);
            return fileNameWithExtension;
        }

        public static string RandomImageIdGirl()
        {
            List<string> listImageId = new List<string>
            {
                "1RrjC8WAzqDKY0AClBiKCXQhmX7theAPC"
            };
            //List<string> listImageId = new List<string>
            //{
            //    "14Qc_DEZIwGS2jzC6LSd03IXlhJk59K3c",
            //    "1XX3mwNLX4RTugIKOXSKjvpZWaF6k4Swh",
            //    "1kOYbrn36eJPT6m8IZ1jaWBnyoteshthY",
            //    "1nWiV8NAT89SXRFvdJqeSQh8UuNXf2uw2",
            //    "1rxYAMmXuhCzgOjl1YPVXr0Et7XCUAEpr",
            //    "16TWXC2XpTXoyYVk4mFfaO3DZyGV6FSPQ",
            //    "1CA4pqo7aH8B--jDWpTeeqRCKXfomS4jA",
            //    "1la9F4o9HhilhQzYlQ0yjJR_8WyQDyMI9",
            //    "1lstlOfp-HjJavxDVOPPEAd2jbSW1fiFf",
            //    "1F_1vYnYeG8EqleVuM1U3Jpjck9-Ua0_t",
            //    "1UAo5fIicdhjh4VZsnMGhHJNbGhW66DpY",
            //    "1dyUTZ4joCDmRVZ6-nEHnG40FkKswj8g8",
            //    "10UdLW2jXuDy8l2ONqC84U30PYVk0i4xX",
            //    "17qX7QnMvKaZG286RjlujKc2dRFXwSF_p",
            //    "1BimrRPRNM_ggEioGjWH-IWXJlNlZ3knQ",
            //    "1DkqQl9cu2-1scqqcOLw01iCptGGuot_P",
            //    "1LU0Rr5_XV5puKJtaqc-qf8SQbjttFjbv",
            //    "1Xz1FHY_tb3nLUaTMS6eKwbxAoCXPHKxz",
            //    "1mW-1aWFccU-fopfA7Y-Xyj3KBuphvcq-",
            //    "1wcDSSMnO1sPfQja8mU-3nH8CBqnktHto",
            //    "17V7FuuX9tLmyjn8PLGGjHigj36-uzOZO",
            //    "1DMOc54danqFioCF0D70QA_h9liHyQiYK",
            //    "1m2jQb4NXXX0cq8yk46oE08u7WTeDYi4r",
            //    "1NKFIzja_wcAn33z8AaPkDV_fPRGD0-of",
            //    "1ZHtkRX7bXGYuOfWpyo-3i71nWiP4CfL2",
            //    "1cpQa-0BNkvxjVbTl9KupxpnkmrvnSwNK",
            //    "1gSOr7vQu3Lg6o7pK4FvTNxc8tmvUxeP9",
            //    "1jIo0VM9h6TJXhMlSu4bkbf7dSXC4LpAl",
            //    "1oz8a4tkViJdIwZ1vcnR8a3gLgMSwee0B",
            //    "1sYopgta4BwnH5xaDCAn1f-SypAVn0u5m",
            //    "1sacPeoFiqejCbZhA2A0fnK8EEut-__15",
            //    "1ypYcbaW52OY-0po2XAzZZVN3UP2czBOj",
            //    "14LIOLm9MP4KFVLaft_fl1awHJ7KNnaJ4",
            //    "17N9vm0jrB_FznN15g25MhmvUS7_Kw6Oh",
            //    "1Kw-Wy1hAGvG8FhtZuImhZTJLKt58Rd5o",
            //    "1S2DlJqeVSXtS3vnA3fo6bYz1onTftQOh",
            //    "1rhv60_5vUdFWnssDslz3aw2rwmFKTeff",
            //    "14mTeZJ6qiToPt0rVhA4Jn9l2LTt7PxKy",
            //    "185BfvqubD9MZQebY0Kc_aVkwgxETmlkb",
            //    "18OCQ7V1o4JABWvbkmfrNAGm_vlmpbgTV",
            //    "1CHGNJ0An6ZzuAbRTPlvR-M8gVNeS5XFS",
            //    "1GZPiPqvwkaXFBSfcP0njyv-XGtjHl6M_",
            //    "1X6J7Tpm8EvUNsvHZrhY9sgh_JVbiN92E",
            //    "1boYhnxbQdJWs3ysH7h8TMMvvksA6_yuf",
            //    "1fK5iZQPza7vI7gyhteknLNwN6hnineFJ",
            //    "1rwZFZKCTy29YKOm9A8dbT5Ut0N45K9Ik",
            //    "17-L8VWMCbwLkMTp-7p-YurKDjd1-uvaE",
            //    "1HNkJSDyu7BbBnUlbgRGjfwFVVxzXQudk",
            //    "1VJYI92GHravwdfszotKNUVRJAOG7o5Xl",
            //    "1VSfEQGNhSEEnpidgZvJmBofMd90FZwXB",
            //    "104JpieKEC7kOR4fqXNDX5OKvPLHdQBaS",
            //    "13ZRASjbhTamcc4zD1rqdi0OE-ShxEvUp",
            //    "1J9CizI88J11M3tvBkbNgA4hFi4sWUYny",
            //    "1JGT5rIjI_x6pti-Q6MAehnPIIUYQWweO",
            //    "1NagwyVtZiQfvEpP1aLhsvLl9Gy7xXqO8",
            //    "1WN94qB_gt2CQSIdg4M7atjpanpAuFiEU",
            //    "1YxxW475-lLw-tfquqv_VuyMk8oh5sHx_",
            //    "1g2gyIqymLocjWZ42pbk7TY8nOKun0ISX",
            //    "1n_R3WnQih1KGbQuAbldzlZlbXVZYJyEG",
            //    "18Ai4lNeuf9GHtJWrOsfDyn008Vmk07aD",
            //    "194F1PH_e7GSAHFBMcpbpKc_cwuxDDhvZ",
            //    "1ZhcUuUzBU7d6gDknhmNMz1bkzz_q87b1",
            //    "1W1dDSTXYOeVTT287lXKiZzosQAj4O3sQ",
            //    "1ZQHAxNmg8vL7WGbR-rTT2scwD4fYi_n5",
            //    "1ay8y2uZfTdCP60gbL3xi5CPLzMoKlCAf",
            //    "1bqKYBXjiPUf_IqdPaS1W9OkWObnV4TSr",
            //    "1lMdDVJcbJyc0pzX0S9610Iic5fVnd8Az",
            //    "1s9ekhtGb3rKUhwHR7IIjaF96MOYuX2o0",
            //    "1A5YB7ii4UoWWVkEdfXRtVfqjbGvHI69i",
            //    "1LmpOdZeIrS_pdYQrZvTXP9vkPZEgjizl",
            //    "1RCCXiGXQPfCJJE9Gh0BvBmEf8ybnBhUk",
            //    "1xVj4wDYN6o8DNce7NchBxfHm0MF70t1K",
            //    "15TR1z340wnNzHdeScaCjiynbp4BDuQsn",
            //    "1osj0ehgAjyubgnrBurGUKPSbUx0OUuza",
            //    "1yunHnvQ1Pa7KRd5Af_p8kVw93YnLU7fd",
            //    "1qvWRivThMi54kxjyD7_Aeq90z_beyyCi",
            //    "1wQLsHY8bBCujgTl6LAMQ4YcmfnydLWh6",
            //    "1CtNkcrUs6sknQZ2ybEt5EZOtNUsJEKsb",
            //    "1DahBJEV7gTq_lYzOVuMcJ_VubSMt7J6b",
            //    "1M1ui3ESVE8x5f9eebrKhXx678VKH8ScD",
            //    "1Pa3ApVG5DSvDlLI_5VnjrDSiy5D9Rp09",
            //    "1ZD9_1w5YBjwmSfRH3U_RTJwaN-azxsJK",
            //    "1a24LS6xyU__8mHtm5fL3tcwbglXbG-9z",
            //    "1c788VWtip60GVC2TVBivE3OlIjmmivBe",
            //    "1frFkJxOl3FZtkezY0lVLgX35OLB2WVKW",
            //    "1lP1CWyUDQaoPVCdID_SbRuESxZa-ZLrm",
            //    "17wY0AD-jk8j4MCj2QWBe4YU291eHnwyg",
            //    "1lcuVHwZqz8CHmu3v357Kh2Zuzai-FAHo",
            //    "1oRPGluzJe9f_Dvae1FiTGCjFY537pVj1",
            //    "10FHIpz32euBr9KsBzR14MpEMMoO5lpCc",
            //    "155OvEeGzDlMqJnalHmefMBaUT7oEJ9hW",
            //    "1Cgj1Clp9bG-ujYjTg3UX91Qqwdop9jBX",
            //    "1KKTht8NzB4yBipgmThZAtesQNMxInqwJ",
            //    "1PCgGzQRdVe-v0CQy2ecOb7Y0SSkhOic3",
            //    "1YODXiWac6RxguVUyxr-6kNpMIQf7kvJa",
            //    "1dBJ_2gmeQ4UFG2KJN57OlvYBj6i8CtNw",
            //    "1jo2uPbsY2i7LBej6VGcWSwWhKnSs7MPQ",
            //    "1nWj-9MnsD2dBpd-juvAl0_Ck7_bhv4oR",
            //    "1wppXg5hPKwDd-lhdQxat6icko-IzaJll",
            //    "1OHUctfQbtrf-E639-1SAxF-iAKiax-w6",
            //    "1WuCMR92SUoIwZ2xzqjw2PkXnROOX7Fhv",
            //    "1YNGzYD5X9M-ROcn8EvhyAoCRAy2O_DZK",
            //    "13VpIUi-8FVkxG0dfSpEBbtzRT-52JTvS",
            //    "15ewyFJNrCXLD_kUnUzf_zPPOv9wTM8iz",
            //    "16XtQKRApWBKwPON8oj96agOn1PUtVj9j",
            //    "1RiHPx0ZfO41DvEz5yBpWaPDF571MXXHc",
            //    "1TNNhS9OhK9cDw0dOUOyTLPI0h8USoSkm",
            //    "1VqOYrUfhCKjZBW-EOCwybrog1ODdzI40",
            //    "1zZMyYEuPlGI_E1imWOhjG8OG_xbsqUmv",
            //    "10DzH74XUd975ZAZKJXtMnnHxBOf0omEB",
            //    "1CqXicVhfM26K8u4p6AQypsK00yFVh3JV",
            //    "1KpWQShHZdWP8nwna9RD79-cQWfmCM8OH",
            //    "1QWvF-DRFIaPbV7NROLefj7blx6zXQa0p",
            //    "1D1feksdhACp1kle7B4N4VN6v-FyenC8g",
            //    "1Qeb7mVCq82l7zvp-9iDeqeYJZWDSkBLM",
            //    "1SogpnbpsL_5Lz9QQb9yVcNg546QC98Wr",
            //    "17Xc1nxtctQil5-JifmTFtrFnyOHrpFiQ",
            //    "1AYup_ugniALJFRJ9OUrbQXxNbbEybsGT",
            //    "1DCp-AgO9ljmPOqY_urir1EbRvSHTnlyr",
            //    "1OdQ66Ep4_maZBGoRGwbptHcx8rmfBT3Y",
            //    "1X-KZbAv5AkK0OsPOFUCd6kCY8UZSPOqC",
            //    "1d8Qp2Igs8HRKKCFmT3q6-5FTAejjl0MA",
            //    "1nYx1SVnFuS5x0mT93GJK14vzwD4pOL_g",
            //    "11YYhruGdp9ZqHkc8ECco8oceuW1bks8b",
            //    "14nRkmypfsQJzGK2NLLmn7MzplH19qOoC",
            //    "1AFVTU-TELv8cpN9GB33TZic0KhlNidDP",
            //    "1B0ZeaZ_3NbcfB3D-YLikZdf5p66o-rdK",
            //    "1ivwSWB_xd6BCEKZCkUpWT5x3urpjuPNn",
            //    "1VOVcp97unP1YC-4xRMHYVdb9lAH4z0sY",
            //    "1Hp0ArgO4yL2wWArDNjgasPAayJ6cW5fI",
            //    "1I6kfJTczCzDLgIr6Iw7pEYvYat2kKgGK",
            //    "1K-w2unb5FQj-yYmuEJLYxdOadvR7Ywdh",
            //    "1MmT33xDONYL23HIpN_mD1BTfDP2ygtqp",
            //    "1hra2OfgOZMrR0Fu7c5Rm6ca4aECjzko4",
            //    "1znkgl3g_1jnJLveNK4MjPMSb_8-82CLG",
            //    "15fN8gWswj2R6wqVlsz1-RW-pNjixIZ2v",
            //    "1F_F34YEzyzT1pqu5-RneCgl5J38rUHjI",
            //    "1N1v-1dHlsFtLFbs1EJn0eBA40MVINO35",
            //    "1RJ51NeqL9UzloM3TtGtsLEK29UUXGTUT",
            //    "1WPSGEys5qRk7t7HUYHp9wdE7YM-2RaEC",
            //    "139FPGLgD9CPjXY7zMVL4ltwC0pUysj0p",
            //    "19n19RAPUFEyWZsbXFgdV-iWtwdR7ySkK",
            //    "1zGrRuYK0yLyDs0CTC246HqvzS2xMFH0L",
            //    "18QCV1qmCd1aM2CLBqudeNgNNYu_VM_IR",
            //    "1AeJeb-X_xjyjRw23AXR5Xmj16tNpm2D0",
            //    "1FK0KbndRN8fyVGnZ--rXp8fU6IAab5gE",
            //    "1TZraLSRs8pfNiWWn2VJAqp629TNpCMeJ",
            //    "1WYEGM6_5WPrb7eJj3Mz825buOBjgi4Ev",
            //    "1bpoocDS9P_vjyC4Qiin2G4431R_6kHPl",
            //    "1fah5kR9ShyGD9VMyxZCHai3mS2rbIiD7",
            //    "1ogOnd-XW3SOh1r--FEuXzpJsTqwjNJhS",
            //    "1p67pHo4uweFPBpM3QMdErS-SH_s_0GPo",
            //    "1SfUr7HYM8Lh_ki2SBNdFnpEbh_3haPjb",
            //    "1dYSSgB0QZGCcU7XrFKojBM_eaMx4JaaG",
            //    "152F1a5-HlRosLCW2ugDKSD3h7_8nB5II",
            //    "19l9Q8AYlLb7Psvt-p6znSaFo86OzHNRf",
            //    "1DifgVjM88wOd8MJ4rQZnJVlx5aXr1VSL",
            //    "1SEzud9q_gb-VVXYGSkMoBYDsHaEhqLCo",
            //    "1a6emlkPSIiago92xVB3a__3LYxrU6yKY",
            //    "1oBBVXpqr3_Tml_YXAhCihr_iNDBvdO8K",
            //    "1q2_4pz-tR9f6JD4pwCsNk7o4HYETP7xK",
            //    "1128PmkyG64TRQvW_-DtEsTWENhDz3tPU",
            //    "1I6zA_fVuPAuuzDlbDvw5x8ewAHRpp98Y",
            //    "1hb8ELi7FJ2EU21DKWOnkVXPq7kXJdTro",
            //    "1j6ClAH-zzKejhPxeK7py3gfcF-n0kDfF",
            //    "1yAdIyTbn71laD_O0zphObGivT8qi2h_B",
            //    "1Swyk5Ma9J0WnLL_8ssB_eNITTbgjbeIi",
            //    "120EPK07E43-DqNYSUjH5fv2hZC0QJ3mQ",
            //    "19lhfvsU-ANQ0nsZjTX-ID-baU0rOXxUZ",
            //    "1FwI9A1fXYZuyntrhdVOPTOYpTZJJX5HC",
            //    "1M5rI9IkyZguiAayx2BmOCseH03_Wk9gb",
            //    "1VhKQcVaKF_DQjmLdhVU5U0dPzemv-gd0",
            //    "1ZqB1764kTmDcdhNrHwxBBq4vzWJTUVQp",
            //    "1kk9y1SDc9AFBYYGO9bvdmfmqWkQdkGaH",
            //    "1kuP4nmH_M-lHr64gN6IPnnlPoFjo9lqv",
            //    "1owBz88HcZZqoNnzVaPeAVS9_A2Mhn-8e",
            //    "1uYloxE9VcDXJMB-Dfj8IxMxrCrapK9rV",
            //    "1uyMzb1BjR-d6ROgDZL8L-_26r6uvQpFs",
            //    "1QINocxi6Xo1VYR3YjMSqfRQhocVkhU7y",
            //    "1WHp-X0dem-JzzIvLtH1xbuCZkHMDWVn9",
            //    "16gRAvBUVBKy4QEFe_tzffR8MZfVShfMx",
            //    "1Al1pR0YZdmy8NwjNTxeDpEWy1oR6hDXE",
            //    "1NN8GpFu-kdIOPDcH92gGa-DX5JyQe8Ye",
            //    "1calRaW8ZjGUjq2PaImC-m1K02qPEME98",
            //    "1hPf76WrJqkS-T6tKqCYDuJfXDbTVBVTJ",
            //    "1nPf9Vt0Js13ldT1NDBVYkevDxUAYjj40",
            //    "1vlnidDyCmRUEpZLcKEZrcohs4VI9ZgFn",
            //    "126d8AQJjAPY72UzSQfAOrxHJSYaMwPy4",
            //    "1E9wfwJ-CRV4m9EfI17usp1QjCOOAYyCY",
            //    "1km_5XnNdCaNgOl1ZDGfuv5WWOI5kNBWC",
            //    "15INRUfUGdfRbzUtZSb2jBRqs5oREhrBf",
            //    "1Dd3GxplgeGLNnEfgYDACbAlBW7UVCF3H",
            //    "1Y4Yt16FaIZi5wlXQQlJLGXDJFfeAb3dq",
            //    "1hgZf68Vf6Fapi9FO1p9gWnINIFpuI0jR",
            //    "1i4Xa-JdgNhxfAMrociaFk8m_36U4Cwhe",
            //    "1oHkm7jfjuArvpgk2ti1b8XdxSZO1hFOB",
            //    "1CgsQuHo1O3GzUnk8vz8mGmwphrY9Z79J",
            //    "1Oc_p_qWxpA-0XeNQd5tdYgCrUvNJKL9j",
            //    "1RVgZQ4A-LsJcRHlnV3IjagE-6cjRt_Mk",
            //    "1oHQNbTv7UCpwpqry1eGiAs9poIEjKuNx",
            //    "1ma14eYicNZkzJe2uNIXG7U8PLmJLhUUe",
            //    "10m-HLCns1lBfywZptsGfHXJswCzniLPJ",
            //    "1Z1qCUeYtX9LnaKxEQRjn8xFVpgE71DPm",
            //    "1ZI0PivVZeCDe_DK_9DSkoaZ0OBKzz7aG",
            //    "1eJKP6ObL9owi_A7ZhU4Ly9O5s2Lnl1Pi",
            //    "1kf4XgG9ZgL8cVkdJZY4v4rHmLSpDfIlH",
            //    "1lCsu_NdkRTGj1XF7jK-p66bFvxOvxXbl",
            //    "1lTlXDbJ5AlP3AGpjUK02KwB5PdUTqUaF",
            //    "1-0GBGaQRXkp6MLweWpcb1bKq0M4AI4XK",
            //    "1432HwMLxcUXLcgzNt4mb42xESj0-HPBr",
            //    "1N98K3wt4QZrLNU0TKNOOYsNr7w12M436",
            //    "1wvaQyfUaNsLFSzUT_gT1Se5Rxp1AMp2M",
            //    "1Aiv9mjK2SARF62iI-PbPcxonaoIwOOuU",
            //    "1bqehPtvWczYSqMoPx5bQmI3OaVxPUGnd",
            //    "1p7rys4n0XVm0yIMXr0C7Lcw25EL8IFEv",
            //    "12rCNEOtBTqrvP9lKZTDkKG6PnmYmJrkq",
            //    "14OWhgiLSH7sASeTz-YXLoy09h2Iii8iZ",
            //    "14gC09a-e308EH0yQ-4ndi4SpEZJu_wS5",
            //    "191dwVrpxpY3JMDojA8vR8z8iALvwaWv9",
            //    "1WRBMBFrb3g3P8lOpnwcvMcWTZLdpMGPk",
            //    "1bLtS3B2Bs331g9sZDRHAMDvI2BdTdunj",
            //    "1fMhkQcNatXQ2trpdcuB-xDJukqXzzPVy",
            //    "1gd7i9nepZpXcoLRIMsVgqeTNFjFmqpb1",
            //    "1yhIazQl2K9iw-K-4Ng7pgVZDqhN7bNsC",
            //    "1-iOgP8AItpUmLJM3pO0S4L4eYsxrtlF9",
            //    "1TCb-JESS9kT-Mk_Mh4ntjyCG63021LuF",
            //    "11zitXaa8m2oOaNV06ETwBs91cCJTxBas",
            //    "1HSB3S6y8rJ345CBN313XotgkOJjL58e_",
            //    "1MqzE_XfknpzZYaXt6AwBQ_seACy9l1jG",
            //    "1dVDUz06yUe8fLJ9Yx-21jyQ0-9cacfU5",
            //    "1nCr4aQ3K6qgYSlRP5TvP4NYtAOBK7Sfe",
            //    "10HjY7ffkBBLS0uIuoMOb-wKxSikHHore",
            //    "11NGf_dJimjY-L6ZfDt9s79O8U33D4aHE",
            //    "13iIDqbCHvBqyI5QAXQRlcz8vLw0N7Wkn",
            //    "1GaLoGUQ2zYX6M6_ZFjyhSkXY5IPCbr3X",
            //    "1Hq0LW_mIsm7KmrvqNlQU2VOBfH0h4LP4",
            //    "1LCrRobjR7m05K27WtNKZwYxpbdu1UTVK",
            //    "1eYWJtfiNaI6IsD6kTydJe_oQxji_Ltn5",
            //    "1iqu952xZjHkayTOLHtVjRpgu2xsSpW-Y",
            //    "1oWQcSqdFEz1llsYO0NVJi_34kOmzE2Ak",
            //    "1w6Bccu-DxBE4Jd3MmcfnMnRk3RZhq56i",
            //    "1L-MphhD3QU2t6WcHuJqxRQdxTBFoBVEB",
            //    "1w5cxvY0ZwckJ26BWjeAdkwB3AJXIYOOB",
            //    "15Sy9nWOGUC1ejiSDuDfIqJGxIEofe5kI",
            //    "1GuRAJkk8GfRQWosDZd37Bo5nXogV1h7T",
            //    "1H6ZALX1M-qOQb8JOZ_ikESO3jPsGtsTg",
            //    "1_7fbaiYsH6_8KSaLQ6SGlO5ZIst6GJrm",
            //    "1nGlxWU3ZpAijzmR9xG_y-q7H3RiR1Eb5",
            //    "154Y1FHJmhVEi8grVw9FfJcRy_GQSXl7P",
            //    "1VD1MH-nbv8bcpf79O5bkkdkeWKO-ehob",
            //    "1a955O-Ocu--WQyN_m591fow7wXopIVbD",
            //    "1iVo-TtBdJlrpLw4o5YBZsZAJ9-eI8Zmr",
            //    "1jx6G_Iqx1ZFmrGP6Y18wDjpXgSAPxTvU",
            //    "1m4CUHZJXu_-DlJEANFWW4f9Poy37BRo3",
            //    "1t82YwVMkJZhs5XCEcmpJP0EcrBxe5cxY",
            //    "10umAGmAdwwWcUeTNK9yT_iuf_O-CPp5s",
            //    "1m-L4L_o4RycSdlgoeA5haiLq1euxZqa1",
            //    "12Uc0fZ1KJySMS8nr3E-Tw2itA9dkDjm7",
            //    "1EtsPUJpqj4mTvuCCU9udi0yW3EdCDCUA",
            //    "1LRBkuuAs27pTTFtRJ7CI8wpp8dlh_chz",
            //    "1OP7lqJFx1HuQ_r-FE5k_OboIepdE_AEn",
            //    "1WSYOA9yq8bKqMSwP4VHxaOn5mjZsxv9l",
            //    "1b4o7xDNPWJlEtK-mnaRnHOSflvc0EqDl",
            //    "1ngVxJ41rWPy6fmSlPi3JUueLmV5-zKpf",
            //    "1s3FiSIeaa8ogeJTht1LfQnKOSilhv2Me",
            //    "1sYaqKMHLtm-G_yXBWhvOhBbbhRBPtX-m",
            //    "1tlfGnZLtHvbc0k4Jo2FeeD7RpGXzK0Dh",
            //    "1H1Mp6fLwfhes7FGNeFv59b-zBM4WwHK2",
            //    "1eSObJwMI4QrOjpyMjUVdIUrMpKLcFvMX",
            //    "15jOI4kgepx9SAOCKQv9fOwE7f5MLl_19",
            //    "1BNtskNEufC1hoSrgc6XRuoVpiThCneBT",
            //    "1EMnPiMYb1uebqpBiOTj4sotYGbRq953b",
            //    "1JHecfHd5itXEc9SeucxGcXhBC9BknfXE",
            //    "1Jj4LmIyUyaNPGHbKxqh9EEg7WKhSY-YA",
            //    "1Jl_2ZDQzVgD_pNf75hME6XSWNmAA3Thb",
            //    "1Uk3VOUz5DZDB2SPEVhrXbFIu5GxZuFXz",
            //    "1boMhpyyl9SjlXNd24WvChQUMpSqTzgH9",
            //    "1dLK6cSoCYI4Jgx2AXgsrGu6nHgutzZWb",
            //    "1nZQRa-95bCBAXv9X9V-VzT_wV4P5wdgO",
            //    "12l3yyIOnSDYSqJcGWfn2WJ22oLP9MTrF",
            //    "1wvnVmopcwyAU_kiPw-xTvZ7Ja1XidI9x",
            //    "1GbmMR4ryAf03firo7HfEx7j1T6WDl0q5",
            //    "1HERkeLMsYoLuwcZE1ndgMXZQR8XYddK7",
            //    "1HbZIycpBTrK5UboLbR6oX6cYHuo_HQL6",
            //    "1VVAzTCFsBBVQsjr8vod9uAdrB7lqP-75",
            //    "1gU-RLTrZ3xKBI5pZBQkL2Fk8CEe1lbwu",
            //    "1imNitIYn9o4AszcSJP3lwKY0eBih5MTo",
            //    "1liarJxuaF6F_R4HKk7SoQg0Q8pEgg2yR",
            //    "1prnhkzBB3JPbKjw9iE8dXMvDGqDOBqAR",
            //    "1xEidzHAp6UCRZA2xpNW87ZznRPKlb_bz",
            //    "1zsB5_HT8mDJw5zMamUiL8u2sXu-2VbtW",
            //    "13kj9YYxnd3Y9bIk1SCF9iX9elxm8JuTt",
            //    "1LAMKvTJB0wE7O9tYx1KSI5Vm64aI4bN4",
            //    "1O8KUW9ETh55xa_b2yBUehABBfmuwvaOZ",
            //    "143gDbSsA0jfKz5ZCQREj2YxPfEUAxXaG",
            //    "15n39yN_9Cec8v8HlDYpjzfavdMIcPJrV",
            //    "17E4kqxv8CUBN2mG4E4FfBbMBNwPTXHws",
            //    "1KFLoGB5gfGS5pTRF6cr_UP57MflyJH0l",
            //    "1KGjoUrk9T2P-QuqwOCkT-CYK9HVaqJAa",
            //    "1hAFacgOT4wcesaCZ1RarjDmVXxyVMaw5",
            //    "1rPDLP8TaXRV4kUrN65RB3ZqRcAGEcBve",
            //    "1SJ968eNQf25tCrNivQs1j8BP9enacKa_",
            //    "1iiJQv02dMOyPBAe57LfpQSECfKrrh3iw",
            //    "16Z8CNrp61bNsHJfrybC1K0MzZBGNfBXU",
            //    "1LFBe3SBUB1485CeNtmAarywA4bX7uDDC",
            //    "1T4G-iyaakL94PZtQ57nT328fv7AW0roa",
            //    "1ZcF7rItJoG6lCn-JgYrh__umUpBeW0io",
            //    "1JTQvrAXkcgZXxB_PBZ-QBxzbo3PGITeA",
            //    "1RejkagjxKF-fDx1Kr_un_s64ly6Fu8jo",
            //    "1esaT-nLjURJXfjj2ZP_3kZ3uST1xlcj4",
            //    "1lqaHyzzLFOwdRjV6z8gecxWd5KZs4C7T",
            //    "1nh8K5N2IS-GSvrxsBHQsvR5NdvOfm0XB",
            //    "1GaKyFNJfJNXZ7_g9HtaasklaQZwHNz6I",
            //    "1QSGA_uIjdE2aFu9pMKxVQRkDObQ4ioKQ",
            //    "1QXRmjcCY-eAUg788LeBd8tye9ITrXNMe",
            //    "1cTpRyEt1cnkZmPWEXOeLkRIeCHYbz08h",
            //    "1ffPM9zvyX1a8PTdGAcWe_iHLiOdDKIDB",
            //    "1unQI-H921Tyf4ZPc8goY9cUwzs0OTa2a",
            //    "1K93rcvcPOlqf6evt9Rs6kT_AC-vDXA_3",
            //    "1KJngcPLQDmTZLhh96OJhT6d6T7EuDwT_",
            //    "1cf9hScp4FIyWwQbC3tf6gVWl8_Hq648u",
            //    "1Gg5khtINbUIFbcv3PvsweaKjDRPrfwZI",
            //    "1HXxZtqhN-dS98ixNyGK3_Lup2PPQmzw4",
            //    "1KXgTxpWXObdh30IVoQuDbX9L6IHQkMND",
            //    "1KaA6V_YFw80stYmP0flUSCZQyd6ksVBh",
            //    "1Ke44wf_b_F7IJeuxFwZ2otNlGObLxkrG",
            //    "1dJP-QnlnCOyAtoywH9yg86jZBSS8XHA_",
            //    "1t-SwwSfkgMyOP0a7x_xTdYv4SzS8zbMs",
            //    "1x5NFE4RpLNeSRsDT2LAC9nB2g7iMEFl_",
            //    "1xsImwFS9H0vs1eZWF2Ze8SCjncwQgZpd",
            //    "193gG2kuQBlUCSjqXT5HTyarmH7OcNeoz",
            //    "1Tv6e9CUdNtCe-XkR_yHrm_mqydM4Yp5f",
            //    "1UzCHKrPNi09fbCmv05tuqClQ64O_ho3I",
            //    "14bHYKyyn6Tlcci-Tq41T8pgumsz8jDE4",
            //    "1mOwP_1KLvuTfxVfnwkSuOI3kr-QAfthg",
            //    "10lpnQt0Q7c_VEXp49fKF6qLGZ9ZOdJF5",
            //    "10vQC7MXG2DidjtiDC76W5wq8Gn2Yi5Kg",
            //    "11XjaUhbjPN5oXaSrrxL7Dw8AQbdqCN0V",
            //    "1DK7MxVSaHL30XACTh0SR3a1BIfMZJEbk",
            //    "1DrC6FyA2yWh4klYhEnnED1ikihii07B9",
            //    "1FXN2ZvePQwTICm8TanlmuOtZmlgXS0Fd",
            //    "1MR_sXvU9g8eZKdE04AJmmAhk9kow7lnL",
            //    "1Qzd511Bal9YI1sxCMhQbb_IUAeUn8UIR",
            //    "1e3_emKpTgUyzCU2s6TZtBsF5AS9IcGaH",
            //    "1PwduGePAI98UVfP1-SiMy_flc5aIeQps",
            //    "1YPKPOiuaDibp6GXd2ScioBdzBjQ12jQu",
            //    "1-vwEg9wM6AEo-642icJA1w7uhalgT9vK",
            //    "11QEtX7ca8eOlUwylT6LEw8BYBxfq_f5_",
            //    "17LnyY4bAYke-JmfNb2-AX-eVPhwmZT4P",
            //    "189HEtYdTFOCxFjfY6UHKPCNUqDkwkkUI",
            //    "1GVNVsOa-ntTk9c8C784XRFjJ6entXgjc",
            //    "1QsHTmE1vHzIV__vdUwHlUmi5hEqow1Ru",
            //    "1UqQpU6i1gPDoGAPG3Qk3PFGJ01pysi6E",
            //    "1sNT2oDG_MEwDc06tEeoXM1dvDbBgwiO_",
            //    "1x4EYfWwFJ-acnY6HqzE3dib8v1gcE4Su",
            //    "12BeLOp3oJgdA4r-1TCuMDNDe6QAxRuGV",
            //    "16LvmWuAmIRajHN8TDUSmQbZnzbXeaymB",
            //    "1EjlJlk9B9II0sUtZ2fEjQ9VTbip1sgeK",
            //    "1qXWQAwVadposzKQqW6hsDjTTaLcbaibt",
            //    "1DEV1V9_LxE_YAVSeiYm6OnM4XtKSoP1P",
            //    "1QY83z-xT1u-cwMIbKLI-CYm9k9osSZFZ",
            //    "1XH6muzJ9RV7shgAMTzSer1_ZshFyVVdH",
            //    "1_DOc-hOPqJbv2qRkPz4gvuazbb9UvO-p",
            //    "1nUii82AIQI8HILgjlP34QJrde4ULs9WC",
            //    "1ncYJ_959Dhsi-3a-IJQiQAaBveGLpN0b",
            //    "1njrBHoQN7HlAFoxej86NYxgz5qFSG39F",
            //    "1pIhGl-KYTxjSRyJh4yFdb_dxhddkzPUJ",
            //    "17U0Gc1qmgjG6H5lWDweXtdQPE2f6h_Y3",
            //    "1S1-ZYb81YE8fZRFjBD8XCMf6JKFWxGyx",
            //    "1FA18ZrrmdkGNAvLWk-MIGv0mqB6hMWeF",
            //    "1nHaPxhcmhL0xeHlhWRevpxxfgavzWSQf",
            //    "1zfWVM68s4tZe-U5CkAs8AdubeKIRn4pn",
            //    "121Z2YlhvArl17dKC2PB5mqaP-0BD8KCe",
            //    "12z640G8WhN9T-nQsOGx5MitTa_npsUP2",
            //    "1BJjcEpHhSAiV8Vynv-aCKJ4z9kBLYHH1",
            //    "1L7GX7vAOcRic47rVz4tiRyg-tP66txo7",
            //    "1LwShDwPdwWJSTLMziV4pkyCfiN-MTYsu",
            //    "1TLD-EOIDSjBw50Yf2iatPDayBslIrsnV",
            //    "1TSEZHrtAkhmaNWCmu5ijXbsukRGBdFFD",
            //    "1ZpxBeB9qzHjlTCQJAP8uDhizXmjdP2XJ",
            //    "1pMx6SCK8mqfQWJ73CR8rMkT3Yf9hh5I8",
            //    "1tJlcJQ2zrhPE_DWtd-u3d4gavgIuAMnd",
            //    "1QTT0wkmEC_K2mmL4SrmRriGogvhWeH9x",
            //    "1_TpzZ0TwqWJMgF2tVDcyAFEi24bCmUGf",
            //    "1iXuDdhJsdNMRZ10BA0mRbwUYYVug6SDI",
            //    "14dgwVdeEUiDYeyUo5EjxwSUcwVG3EqPo",
            //    "1AzGiW-WFpsnM_h9qkJeNuWYyXA5PfJT5",
            //    "1B_NX3UEPA8XU4VrxpsWv6V1OxfD841u2",
            //    "1EE-lVAh6nv2TL3YjRP0fS7wtdyvphmhl",
            //    "1Lsc-OvPtn1P2tn-O-Hkr1U2wzzxPbqtK",
            //    "1NnY18RtqMk1HERJ7D8nP1ZbmrH3U-LYW",
            //    "1_3rAoWlFv-urt1V87LaAhfm-w2ai-gh3",
            //    "1eWd9NNLO1WB-kglWVqMV3zerg_scFJGS",
            //    "1vbhiKWSIbstNPms_ibVfaDjWigRmZkyV",
            //    "13pUR1VxBYS2XJHl6K94ETp3PVAHrDC8A",
            //    "1kP8Kutjr0x3EhKbFvxILlb8GFbLT7bP9",
            //    "1weUGef2JKjBwzxoQrSfFQUG4C1y0bydJ",
            //    "1ISmRCKBhTuwHrx-MjIzGN1lm3XwGDRM-",
            //    "1min3ZK1mqZLGu88O2NCw4nX-e91zweah",
            //    "1U8GSlBPA5tbIfkm_tv3KiOcFIWSFbndR",
            //    "1x4yIl_TryBxAX96kxrjMSvoUKlQ1miuW",
            //    "1tndi8l8xYNOiDrqjp3nFBSffOwhco1AX",
            //    "1F_eTc6PpziHwlXb4aAJmVIJ5Ft-zoxem",
            //    "1awQt3BCPGtRA8YNW4HinKpm-P7D4l_CZ"
            //};

            Random rd = new Random();
            return listImageId[rd.Next(listImageId.Count)];
        }
    }
}
